# Generated by Django 3.1.7 on 2021-03-05 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210225_1716'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
