# Generated by Django 3.1.7 on 2021-03-05 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'managed': False, 'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'managed': False, 'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='basket',
            options={'managed': False, 'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'managed': False, 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='bookauthor',
            options={'managed': False, 'verbose_name': 'Автор книги', 'verbose_name_plural': 'Авторы книг'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'managed': False, 'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвета'},
        ),
        migrations.AlterModelOptions(
            name='cover',
            options={'managed': False, 'verbose_name': 'Обложка', 'verbose_name_plural': 'Обложки'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'managed': False, 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'managed': False, 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'managed': False, 'verbose_name': 'Тип переплета', 'verbose_name_plural': 'Типы переплетов'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'managed': False, 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'managed': False, 'verbose_name': 'Способ оплаты', 'verbose_name_plural': 'Способы оплаты'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'managed': False, 'verbose_name': 'Издательство', 'verbose_name_plural': 'Издательства'},
        ),
    ]
