# Generated by Django 3.1.7 on 2021-03-05 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210305_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Показывать'),
        ),
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='В наличии'),
        )
    ]
