# Generated by Django 3.1.7 on 2021-03-05 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210305_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='available',
            field=models.CharField(choices=[(0, 'Нет в наличии'), (1, 'В наличии')], default=True, max_length=10, verbose_name='В наличии'),
        ),
        migrations.AlterField(
            model_name='book',
            name='stock',
            field=models.PositiveIntegerField(verbose_name='Сколько в наличии'),
        ),
    ]
