# Generated by Django 3.1.7 on 2021-03-05 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('shop', '0008_auto_20210306_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderbook',
            fields=[
                ('id_user', models.OneToOneField(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('is_ordered', models.BooleanField(default=False)),
                ('id_book', models.ForeignKey(db_column='id_book', on_delete=django.db.models.deletion.CASCADE, to='shop.book')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
                'db_table': 'orderbook',
                'managed': True,
            },
        ),
    ]
