# Generated by Django 3.1.7 on 2021-03-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20210306_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbook',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
