# Generated by Django 3.1.7 on 2021-03-05 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20210306_0054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'managed': True, 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
