# Generated by Django 3.1.7 on 2021-03-09 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0018_auto_20210309_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='id_book',
            field=models.ForeignKey(db_column='id_book', default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.book', verbose_name='Книга'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='id_feedback',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateField(verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, max_length=50, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(verbose_name='Отзыв'),
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('id_user', 'id_book', 'created_at')},
        ),
    ]
